### ISSUE TITLE
Database Manager

### ISSUE THREAD

**Issue by lingzhang-lyon** [robertcao/CMPE275_Project1#4]
master should be able to store meta data for image information , and for slave health information respectively.

master should be able to upload/download image file to/from slave.

**Comment by robertcao** [comment]
Complete upload and download methods.

TODO: ResponseFlag.failure

**Comment by robertcao** [comment]
Connect remote MongoDB:
http://ghosttx.com/2012/03/how-to-connect-to-a-remote-mongodb-server-with-mongohub-for-mac/

**Comment by lingzhang-lyon** [comment]
1 file format issue:  
if upload ByteString directly in mongoDB, then when download the file format have some issue, could not read.
2 TODO:
the download and upload method should be able to store file to mongoDB with specific socket

**Comment by robertcao** [comment]
I am dealing with task 1.
What does task 2 mean? What is Specific Socket?

**Comment by lingzhang-lyon** [comment]
hi, 
upload and download has a parameter socket, I mean store/read file to/from slave with that socket
